"""
Enrich docs/descriptions.yaml with LLM-generated table metadata.

For every table in docs/tables/*.md whose entry is MISSING or STALE in
docs/descriptions.yaml, ask a local LLM (LM Studio, OpenAI-compatible server)
to describe the table. The answer must be valid JSON; it is validated before
being merged into descriptions.yaml.

Staleness: entries generated by this script store a `columns_snapshot`. If the
table's current column list differs (column added/removed/renamed), the entry
is regenerated. Entries without a snapshot are kept unless their description
references a column that no longer exists (backticks) or `--force` is used.
Use `--force` to regenerate every table regardless, or `--views` to rebuild
only the AW view objects (v* naming).

Hand-edited entries are protected: an entry whose `source` is "human" is NEVER
overwritten (not by `--force`, not by `--views`, not by a schema-drift rebuild).
Pass `--force-human` to let the LLM replace them too.

Entry format written for each new table:
    "<Schema>.<Table>":
        description: "..."
        domain: "..."
        keywords: [...]
        questions: ["..."]
        source: llm          # switch to "human" when edited by hand
        model: <model name>

Usage:
    python scripts/01_docs/02_enrich_descriptions.py
    python scripts/01_docs/02_enrich_descriptions.py --limit 5
    python scripts/01_docs/02_enrich_descriptions.py --force --limit 3
    python scripts/01_docs/02_enrich_descriptions.py --force-human   # override human entries too
"""

import json
import re
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
DOCS_DIR = ROOT / "docs"
OUT_DIR = DOCS_DIR / "tables"
DESCRIPTIONS_FILE = DOCS_DIR / "descriptions.yaml"

LLM_URL = "http://127.0.0.1:1234/v1/chat/completions"
LLM_MODEL = "google/gemma-4-e4b"
ATTEMPTS = 3
TIMEOUT = 300

SYSTEM_PROMPT = (
    "You are a concise database documentation writer for the AdventureWorks "
    "sample database. You receive one table's metadata and must reply with ONLY "
    "a valid JSON object (no markdown, no extra text) with exactly these keys: "
    "description (1-2 sentences, English, say what ONE ROW represents and point "
    "at its important measure/ref columns, WITHOUT wrapping any column or table "
    "name in backticks unless that name exists in the provided column list), "
    "domain (one short word: sales, production, purchasing, person, "
    "or human-resources), "
    "keywords (array of AT LEAST 8 search terms, mixed English and French), "
    "questions (array of EXACTLY 3 English questions this table can answer). "
    "Strict rules: domain is required; questions has exactly 3 items; "
    "keywords has at least 8 items.\n\n"
    "Examples of table metadata followed by an ideal answer:\n"
)

FEW_SHOTS = [
    (
        "table: Sales.SalesOrderHeader\nrows: 31465\n"
        "columns (name: type):\n"
        "- SalesOrderID: BIGINT\n- OrderDate: TIMESTAMP\n- CustomerID: BIGINT\n"
        "- SubTotal: DOUBLE\n- TaxAmt: DOUBLE\n- Freight: DOUBLE\n"
        "- TotalDue: DOUBLE\n"
        "relationships:\n- CustomerID -> Sales.Customer.CustomerID\n",
        '{"description": "One row per customer order placed in the shop: '
        'a header that groups order lines and carries billing, shipping, '
        'and totals (subtotal, tax, freight, total due).", '
        '"domain": "sales", '
        '"keywords": ["order", "sales", "commande", "vente", "invoice", '
        '"shipping", "freight", "tax", "total due", "customer order"], '
        '"questions": ["Where is the order status stored?", '
        '"What is the shipping method of an order?", '
        '"How much tax was charged per order?"]}',
    ),
    (
        "table: Person.Address\nrows: 19614\ncolumns (name: type):\n"
        "- AddressID: BIGINT\n- AddressLine1: VARCHAR\n- City: VARCHAR\n"
        "- StateProvinceID: BIGINT\n- PostalCode: VARCHAR\n"
        "relationships:\n- StateProvinceID -> Person.StateProvince.StateProvinceID\n",
        '{"description": "One row per street address used by businesses, '
        'employees, and customers, with city, state, and postal code.", '
        '"domain": "person", '
        '"keywords": ["address", "city", "postal code", "adresse", "ville", '
        '"street", "rue", "code postal", "location", "delivery"], '
        '"questions": ["How many addresses exist per city?", '
        '"Which state does an address belong to?", '
        '"Which countries appear in the address data?"]}',
    ),
    (
        "table: Production.Product\nrows: 504\ncolumns (name: type):\n"
        "- ProductID: BIGINT\n- Name: VARCHAR\n- ProductNumber: VARCHAR\n"
        "- StandardCost: DOUBLE\n- ListPrice: DOUBLE\n- Size: VARCHAR\n"
        "- Weight: DOUBLE\n",
        '{"description": "One row per product sold or used in manufacturing, '
        'with its cost, selling price, size, and weight.", '
        '"domain": "production", '
        '"keywords": ["product", "cost", "list price", "produit", "prix", '
        '"weight", "poids", "manufacturing", "inventory"], '
        '"questions": ["What is the list price of a product?", '
        '"Which products have no weight defined?", '
        '"What is the standard cost of the most expensive product?"]}',
    ),
]

for _input, _output in FEW_SHOTS:
    SYSTEM_PROMPT += f"Metadata:\n{_input.strip()}\n\nAnswer:\n{_output}\n\n"


def validate(entry, allowed_names):
    errors = []
    if len(entry.get("questions", [])) != 3:
        errors.append("need exactly 3 questions")
    if len(entry.get("keywords", [])) < 8:
        errors.append("need at least 8 keywords")
    if not entry.get("domain"):
        errors.append("missing domain")
    for name in re.findall(r"`([^`]+)`", entry.get("description", "")):
        if name not in allowed_names:
            errors.append(f"unknown name: {name}")
    return errors


def load_existing() -> dict:
    if not DESCRIPTIONS_FILE.exists():
        return {}
    with open(DESCRIPTIONS_FILE, encoding="utf-8") as fh:
        return yaml.safe_load(fh) or {}


def parse_table_md(path: Path) -> dict:
    text = path.read_text(encoding="utf-8")
    body = text
    meta = {}
    if text.startswith("---"):
        parts = text.split("---", 2)
        meta = yaml.safe_load(parts[1]) or {}
        body = parts[2]

    desc_match = re.search(r"^# .+?\n\n(.*?)(?=\n## )", body, re.S)
    description = desc_match.group(1).strip() if desc_match else ""

    cols_section = body
    cols_start = body.find("## Columns")
    if cols_start != -1:
        next_heading = body.find("\n## ", cols_start + len("## Columns"))
        cols_section = body[cols_start + len("## Columns"):next_heading] if next_heading != -1 else body[cols_start:]

    columns = [
        (name, dtype)
        for name, dtype in re.findall(r"\|\s*`(.+?)`\s*\|\s*([^|]+?)\s*\|", cols_section)
    ][:30]

    relationships = re.findall(r"- `([^`]+)` -> `([^`]+)`", body)

    return {
        "name": meta.get("table") or path.stem,
        "kind": meta.get("kind"),
        "rows": meta.get("rows"),
        "description": description,
        "columns": columns,
        "relationships": relationships,
    }


def build_prompt(table: dict) -> str:
    lines = [
        f"table: {table['name']}",
        f"rows: {table['rows']}" if table["rows"] is not None else "rows: n/a",
    ]
    if table["kind"] == "view":
        lines.append(
            "kind: VIEW (a read-only projection over one or more base tables, "
            "not a physical table — say so explicitly in the description, "
            "e.g. 'A read-only view over ...')"
        )
    if table["columns"]:
        lines.append("columns (name: type):")
        lines.extend(f"- {name}: {dtype}" for name, dtype in table["columns"])
    if table["relationships"]:
        lines.append("relationships:")
        lines.extend(f"- {col} -> {ref}" for col, ref in table["relationships"])
    return "\n".join(lines)


def extract_json(text: str) -> dict:
    text = text.strip()
    fence = re.match(r"^```(?:json)?\s*(.*?)\s*```$", text, re.S)
    if fence:
        text = fence.group(1)
    try:
        return json.loads(text)
    except (ValueError, TypeError):
        pass
    start, end = text.find("{"), text.rfind("}")
    if start != -1 and end > start:
        try:
            return json.loads(text[start:end + 1])
        except (ValueError, TypeError):
            pass
    raise ValueError("model output is not a valid JSON object")


def is_valid(obj) -> bool:
    if not isinstance(obj, dict):
        return False
    desc, domain = obj.get("description"), obj.get("domain")
    keywords, questions = obj.get("keywords"), obj.get("questions")
    return (
        isinstance(desc, str) and len(desc.strip()) >= 5
        and isinstance(domain, str) and len(domain.strip()) >= 1
        and isinstance(keywords, list)
        and all(isinstance(k, str) and k.strip() for k in keywords)
        and isinstance(questions, list)
        and all(isinstance(q, str) and q.strip() for q in questions)
    )


def call_llm(prompt: str) -> str:
    payload = {
        "model": LLM_MODEL,
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": prompt},
        ],
        "temperature": 0.2,
        "max_tokens": 512,
        "reasoning_effort": "none",
    }
    req = urllib.request.Request(
        LLM_URL,
        data=json.dumps(payload).encode("utf-8"),
        headers={"Content-Type": "application/json"},
    )
    with urllib.request.urlopen(req, timeout=TIMEOUT) as resp:
        data = json.loads(resp.read().decode("utf-8"))
    return data["choices"][0]["message"]["content"]


def generate_entry(prompt: str, existing_columns: dict | None, allowed_names: set,
                   current_cols: list[str]) -> dict:
    """Call the LLM (with retries incl. transient HTTP errors) and validate the JSON answer."""
    last_error = ""
    for attempt in range(1, ATTEMPTS + 1):
        try:
            content = call_llm(prompt)
            obj = extract_json(content)
            if not is_valid(obj):
                last_error = "invalid JSON structure"
                continue
            errors = validate(obj, allowed_names)
            if errors:
                last_error = "; ".join(errors)
                continue
            entry = {
                "description": obj["description"].strip(),
                "domain": obj["domain"].strip(),
                "keywords": [k.strip() for k in obj["keywords"]],
                "questions": [q.strip() for q in obj["questions"]],
                "source": "llm",
                "model": LLM_MODEL,
                "columns_snapshot": current_cols,
            }
            if existing_columns:
                entry["columns"] = existing_columns
            return entry
        except (
            ValueError, KeyError, TypeError,
            urllib.error.HTTPError, urllib.error.URLError,
            ConnectionError, TimeoutError, OSError,
        ) as exc:
            last_error = str(exc) or type(exc).__name__
            time.sleep(2)
    raise RuntimeError(f"LLM did not produce valid JSON after {ATTEMPTS} attempts ({last_error})")


def save_descriptions(data: dict) -> None:
    header = (
        "# Human-readable metadata for AdventureWorks tables.\n"
        "#   description: what the table holds (one row = ?)\n"
        "#   domain: sales / production / purchasing / human-resources / person\n"
        "#   keywords / questions: RAG search + QA helpers\n"
        "#   source: 'llm' (auto-generated) -> change to 'human' when corrected\n"
        "# Entries are merged into each table's generated .md file.\n"
    )
    with open(DESCRIPTIONS_FILE, "w", encoding="utf-8") as fh:
        fh.write(header)
        fh.write(
            yaml.safe_dump(data, sort_keys=False, allow_unicode=True, default_flow_style=False)
        )


def is_human(meta: dict) -> bool:
    """True for entries a human edited by hand (source: human). Those are never
    replaced by the LLM unless --force-human is given."""
    return str(meta.get("source") or "").strip().lower() == "human"


def schema_drift(meta: dict, table: dict, current_cols: list[str], force: bool = False) -> str | None:
    """Return a reason string if the stored entry is stale vs the current schema, else None."""
    if force:
        return "forced"
    snapshot = meta.get("columns_snapshot")
    if isinstance(snapshot, list) and sorted(snapshot) != current_cols:
        return "schema change"
    known = set(current_cols) | {table["name"]}
    for name in re.findall(r"`([^`]+)`", str(meta.get("description", ""))):
        if name not in known:
            return f"stale reference to missing column `{name}`"
    return None


def parse_kind(path: Path) -> str:
    text = path.read_text(encoding="utf-8")
    if text.startswith("---"):
        meta = yaml.safe_load(text.split("---", 2)[1]) or {}
        return str(meta.get("kind") or "")
    return ""


def main() -> int:
    args = [a for a in sys.argv[1:]]
    only_table = None
    limit = None
    force = "--force" in args
    views_only = "--views" in args
    force_human = "--force-human" in args
    args = [a for a in args if a not in ("--force", "--views", "--force-human")]
    if args and not args[0].startswith("--"):
        only_table = args[0]
    if "--limit" in args:
        limit = int(args[args.index("--limit") + 1])

    existing = load_existing()
    files = sorted(OUT_DIR.glob("*.md"))
    if only_table:
        files = [p for p in files if p.stem == only_table]
    if views_only:
        files = [p for p in files if parse_kind(p) == "view"]
    if limit:
        files = files[:limit]
    if not files:
        print(f"ERROR: no .md files found in {OUT_DIR}. Run scripts/01_docs/01_generate_table_docs.py first.")
        return 1

    skipped, added, failed, rebuilt, human = 0, 0, 0, 0, 0
    output = dict(existing)

    for path in files:
        key = path.stem
        meta = existing.get(key)
        table = parse_table_md(path)
        current_cols = sorted(c[0] for c in table["columns"])

        if isinstance(meta, dict) and meta.get("description"):
            if is_human(meta) and not force_human:
                human += 1
                skipped += 1
                print(f"  * {key}: SKIP (source=human, hand-edited; --force-human to override)", flush=True)
                continue
            drift_reason = schema_drift(meta, table, current_cols, force=force or views_only)
            if drift_reason is None:
                skipped += 1
                continue
            print(f"  * {key}: REBUILD ({drift_reason}) ...", flush=True)
            rebuilt += 1
        else:
            print(f"  * {key}: querying {LLM_MODEL} ...", flush=True)

        existing_columns = meta.get("columns") if isinstance(meta, dict) else None
        allowed_names = {key, table["name"]} | set(current_cols)
        try:
            entry = generate_entry(build_prompt(table), existing_columns, allowed_names, current_cols)
        except (RuntimeError, urllib.error.URLError, ConnectionError, TimeoutError, OSError) as exc:
            failed += 1
            print(f"    FAIL: {exc}", flush=True)
            continue

        output[key] = entry
        added += 1
        print(f"    OK: {entry['description'][:80]}", flush=True)
        save_descriptions(output)

    if output:
        save_descriptions(output)
        print(f"\nWrote {DESCRIPTIONS_FILE}")

    print(f"\nSummary: {skipped} already described ({human} hand-edited, kept), "
          f"{rebuilt} rebuilt (schema drift/force), {added} added, {failed} failed.")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())